#############################################################################
# Makefile for building: soxapproach
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Mon Oct  7 11:46:00 2013
# Project:  soxapproach.pro
# Template: app
# Command: $(QMAKE) -o Makefile soxapproach.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
CXXFLAGS = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I. -I/usr/include/qt3
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = config.h \
		coords_ll.h \
		dac.h \
		generator.h \
		genericclient.h \
		mapview.h \
		misc.h \
		pathdialog.h \
		position.h \
		setupgui.h \
		showfrom.h \
		showstate.h \
		showtowp.h \
		siggen.h \
		signalgenerator.h \
		soxgui.h \
		soxmap.h \
		utility.h \
		wavesubs.h \
		wp_ll.h
SOURCES = coords_ll.cpp \
		dac.cpp \
		generator.cpp \
		genericclient.cpp \
		main.cpp \
		mapview.cpp \
		misc.cpp \
		pathdialog.cpp \
		position.cpp \
		setupgui.cpp \
		showfrom.cpp \
		showstate.cpp \
		showtowp.cpp \
		signalgenerator.cpp \
		soxgui.cpp \
		utility.cpp \
		wavesubs.cpp \
		wp_ll.cpp
OBJECTS = coords_ll.o \
		dac.o \
		generator.o \
		genericclient.o \
		main.o \
		mapview.o \
		misc.o \
		pathdialog.o \
		position.o \
		setupgui.o \
		showfrom.o \
		showstate.o \
		showtowp.o \
		signalgenerator.o \
		soxgui.o \
		utility.o \
		wavesubs.o \
		wp_ll.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_genericclient.cpp \
		moc_mapview.cpp \
		moc_pathdialog.cpp \
		moc_position.cpp \
		moc_setupgui.cpp \
		moc_showfrom.cpp \
		moc_showstate.cpp \
		moc_showtowp.cpp \
		moc_soxgui.cpp
OBJMOC = moc_genericclient.o \
		moc_mapview.o \
		moc_pathdialog.o \
		moc_position.o \
		moc_setupgui.o \
		moc_showfrom.o \
		moc_showstate.o \
		moc_showtowp.o \
		moc_soxgui.o
DIST	   = soxapproach.pro
QMAKE_TARGET = soxapproach
DESTDIR  = 
TARGET   = soxapproach

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: soxapproach.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile soxapproach.pro
qmake: 
	@$(QMAKE) -o Makefile soxapproach.pro

dist: 
	@mkdir -p .tmp/soxapproach && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/soxapproach/ && ( cd `dirname .tmp/soxapproach` && $(TAR) soxapproach.tar soxapproach && $(GZIP) soxapproach.tar ) && $(MOVE) `dirname .tmp/soxapproach`/soxapproach.tar.gz . && $(DEL_FILE) -r .tmp/soxapproach

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

coords_ll.o: coords_ll.cpp coords_ll.h

dac.o: dac.cpp dac.h

generator.o: generator.cpp generator.h \
		config.h \
		misc.h

genericclient.o: genericclient.cpp genericclient.h

main.o: main.cpp soxgui.h \
		genericclient.h \
		coords_ll.h \
		wp_ll.h \
		mapview.h \
		position.h \
		showfrom.h \
		showtowp.h \
		showstate.h \
		signalgenerator.h \
		config.h \
		generator.h \
		siggen.h \
		dac.h \
		wavesubs.h \
		misc.h

mapview.o: mapview.cpp mapview.h \
		utility.h \
		coords_ll.h \
		wp_ll.h \
		position.h

misc.o: misc.cpp misc.h \
		config.h

pathdialog.o: pathdialog.cpp pathdialog.h

position.o: position.cpp position.h \
		utility.h

setupgui.o: setupgui.cpp setupgui.h \
		soxgui.h \
		genericclient.h \
		coords_ll.h \
		wp_ll.h \
		mapview.h \
		position.h \
		showfrom.h \
		showtowp.h \
		showstate.h \
		signalgenerator.h \
		config.h \
		generator.h \
		siggen.h \
		dac.h \
		wavesubs.h \
		misc.h

showfrom.o: showfrom.cpp showfrom.h \
		position.h

showstate.o: showstate.cpp showstate.h \
		position.h

showtowp.o: showtowp.cpp showtowp.h \
		position.h

signalgenerator.o: signalgenerator.cpp signalgenerator.h \
		config.h \
		generator.h \
		siggen.h \
		dac.h \
		wavesubs.h \
		misc.h

soxgui.o: soxgui.cpp soxgui.h \
		setupgui.h \
		pathdialog.h \
		utility.h \
		genericclient.h \
		coords_ll.h \
		wp_ll.h \
		mapview.h \
		position.h \
		showfrom.h \
		showtowp.h \
		showstate.h \
		signalgenerator.h \
		config.h \
		generator.h \
		siggen.h \
		dac.h \
		wavesubs.h \
		misc.h

utility.o: utility.cpp utility.h

wavesubs.o: wavesubs.cpp wavesubs.h

wp_ll.o: wp_ll.cpp wp_ll.h

moc_genericclient.o: moc_genericclient.cpp  genericclient.h 

moc_mapview.o: moc_mapview.cpp  mapview.h coords_ll.h \
		wp_ll.h \
		position.h

moc_pathdialog.o: moc_pathdialog.cpp  pathdialog.h 

moc_position.o: moc_position.cpp  position.h 

moc_setupgui.o: moc_setupgui.cpp  setupgui.h 

moc_showfrom.o: moc_showfrom.cpp  showfrom.h position.h

moc_showstate.o: moc_showstate.cpp  showstate.h position.h

moc_showtowp.o: moc_showtowp.cpp  showtowp.h position.h

moc_soxgui.o: moc_soxgui.cpp  soxgui.h genericclient.h \
		coords_ll.h \
		wp_ll.h \
		mapview.h \
		position.h \
		showfrom.h \
		showtowp.h \
		showstate.h \
		signalgenerator.h \
		config.h \
		generator.h \
		siggen.h \
		dac.h \
		wavesubs.h \
		misc.h

moc_genericclient.cpp: $(MOC) genericclient.h
	$(MOC) genericclient.h -o moc_genericclient.cpp

moc_mapview.cpp: $(MOC) mapview.h
	$(MOC) mapview.h -o moc_mapview.cpp

moc_pathdialog.cpp: $(MOC) pathdialog.h
	$(MOC) pathdialog.h -o moc_pathdialog.cpp

moc_position.cpp: $(MOC) position.h
	$(MOC) position.h -o moc_position.cpp

moc_setupgui.cpp: $(MOC) setupgui.h
	$(MOC) setupgui.h -o moc_setupgui.cpp

moc_showfrom.cpp: $(MOC) showfrom.h
	$(MOC) showfrom.h -o moc_showfrom.cpp

moc_showstate.cpp: $(MOC) showstate.h
	$(MOC) showstate.h -o moc_showstate.cpp

moc_showtowp.cpp: $(MOC) showtowp.h
	$(MOC) showtowp.h -o moc_showtowp.cpp

moc_soxgui.cpp: $(MOC) soxgui.h
	$(MOC) soxgui.h -o moc_soxgui.cpp

####### Install

install:  

uninstall:  

